server:
  port: 8090 # 节点自身的HTTP服务端口

block:
  difficulty: 4
  p2pport: 7003 # 节点自身的P2P服务端口
  ## 要连接的初始节点地址列表
  initialPeers:
    - ws://192.168.0.101:7001
    - ws://192.168.0.101:7002
    - ws://192.168.0.101:7004