server:
  port: 8080 # 节点自身的HTTP服务端口


spring:
  aop:
    proxy-target-class: true

block:
  difficulty: 4
  p2pport: 7001 # 节点自身的P2P服务端口
  ## 要连接的初始节点地址列表
  initialPeers:
    - ws://localhost:9065
    - ws://localhost:7003
    - ws://localhost:7002